admins:
- lucydot
- choochoo-bot
choochoo_branch: main
gh-pages: false
gh-pages_branch: gh-pages
instructors:
- lucydot
- choochoo-bot
project_repo: NU-CEM/CompPhys
project_title: CompPhys ChooChoo
questions: true
students:
- lucydot
- choochoo-bot
votes_required: 3
web_address: https://lucydot.github.io/CompPhys
