# Key settings (must edit)
project_title: CompPhys ChooChoo
project_repo: NU-CEM/CompPhys
admins:
- lucydot
- choochoo-bot
instructors:
- lucydot
students:
- lucydot
- choochoo-bot
web_address: https://lucydot.github.io/CompPhys

# User options (may edit)
questions: true
votes_required: 3
gh-pages: false

# Advanced options (expert users only)
choochoo_branch: main
gh-pages_branch: gh-pages

